# .github/workflows/shellcheck.yml
name: ShellCheck
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
  workflow_dispatch: {}
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38  # v2.0.0
        env:
          SHELLCHECK_OPTS: -S style
